version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - cd buildspec
      - ls -altR
      - chmod +x build.sh && ./build.sh
      - ls -altR

artifacts:
  files: '**/*'
